services:
  service-a:
    build:
      context: .
      args:
        SERVICE: service-a
    container_name: service-a
    environment:
      PORT: "8080"
      SERVICE_B_URL: http://service-b:8081/weather
      OTEL_EXPORTER_OTLP_ENDPOINT: otel-collector:4317
    ports:
      - "8080:8080"
    depends_on:
      - service-b
      - otel-collector

  service-b:
    build:
      context: .
      args:
        SERVICE: service-b
    container_name: service-b
    environment:
      PORT: "8081"
      OTEL_EXPORTER_OTLP_ENDPOINT: otel-collector:4317
    ports:
      - "8081:8081"
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.103.0
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4317:4317"
    depends_on:
      - zipkin

  zipkin:
    image: openzipkin/zipkin:3
    container_name: zipkin
    ports:
      - "9411:9411"

